name: Java CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Начало тестирование
        run: echo "Начинаем тестирование"
        
      - name: Копирование репозитория
        uses: actions/checkout@v4
    
      - name: Настройка JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Тестирование
        run: mvn test
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Начало сборки
        run: echo "Начинаем сборку"
        
      - name: Копирование репозитория
        uses: actions/checkout@v4
    
      - name: Настройка JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
    
      - name: Сборка через Maven
        run: mvn clean compile

      - name: Создание JAR-архива
        run: mvn package -DskipTests

      - name: Сохранение JAR-архива в артифакте
        uses: actions/upload-artifact@v4
        with:
          name: java-jar
          path: target/*.jar

      - name: Сохранение Dockerfile в артифакте
        uses: actions/upload-artifact@v4
        with:
          name: Dockerfile
          path: Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Начало деплоя
        run: echo "Начинаем развёртывание"

      - name: Скачивание артифакта с JAR-архивом
        uses: actions/download-artifact@v4
        with:
          name: java-jar

      - name: Скачивание артифакта с Dockerfile
        uses: actions/download-artifact@v4
        with:
          name: Dockerfile

      - name: Деплой JAR-архива
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          source: "*.jar"
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Деплой Dockerfile
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          source: "Dockerfile"
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Запуск кода
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          script: |
            sudo docker stop java-jar
            sleep 10
            sudo docker rm java-jar
            cd /opt/java
            sudo docker build -t java-jar .
            sudo docker run -d -p 8080:8080 --name java-jar java-jar
          
          
