name: Java CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Начало тестирование
        run: echo "Начинаем тестирование"
        
      - name: Копирование репозитория
        uses: actions/checkout@v4
    
      - name: Настройка JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Тестирование
        run: mvn test
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Начало сборки
        run: echo "Начинаем сборку"
        
      - name: Копирование репозитория
        uses: actions/checkout@v4
    
      - name: Настройка JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
    
      - name: Сборка через Maven
        run: mvn clean compile

      - name: Создание JAR-архива
        run: mvn package -DskipTests
